// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmcnpisvpnwfxqnzjngb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptY25waXN2cG53ZnhxbnpqbmdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0MTE3MjgsImV4cCI6MjA0OTk4NzcyOH0.q5QiW6nATB8lWGaCK5pTod8dqbE-esTSv-cT5__G5fQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);